version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: wd_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      PGUSER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${DATABASE_OUTER_PORT}:${DATABASE_INNER_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_NAME}", ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  test-db:
    image: postgres:latest
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - test_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "test_db",]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wd_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web_app:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER=${OWNER}
      - WEB_APP_URL=${WEB_APP_URL}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "main.py"]
  
  test:
    build:
      dockerfile: test/Dockerfile
      context: .
    depends_on:
      test-db:
        condition: service_healthy
    container_name: test_app
    env_file:
      - .env
    volumes:
      - .:/test
    
  web_app:
    build:
      dockerfile: web_app/Dockerfile
      context: .
    volumes:
      - .:/web_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=web_app.app.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_PORT=${DJANGO_PORT}
    ports:
      - "80:${DJANGO_PORT}"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${DJANGO_PORT}/health/')"]
      interval: 2m
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["uvicorn", "web_app.app.asgi:application", "--host", "${DJANGO_HOST}", "--port", "${DJANGO_PORT}", "--reload"]
  
  redis:
    image: redis:latest
    container_name: wd_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec --bind 0.0.0.0
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_OUTER_PORT}:${REDIS_INNER_PORT}"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  postgres_data:
    driver: local
  test_postgres_data:
    driver: local
  redis_data:
    driver: local