"""init

Revision ID: d1616502ba29
Revises: 
Create Date: 2026-08-06 09:57:42.170870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1616502ba29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'MEETING', 'ROUND', 'ENDED', name='GameStatus'), nullable=False),
    sa.Column('ecorate', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('num_planets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('player',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('round_info',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'round', name='round_info_pkey')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('meteorites', sa.Integer(), nullable=False),
    sa.Column('is_invented', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['player.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('is_shielded', sa.Boolean(), nullable=False),
    sa.Column('development', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negotiation',
    sa.Column('planet_from', sa.Integer(), nullable=False),
    sa.Column('planet_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_from'], ['planet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planet_to'], ['planet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planet_from', 'planet_to', name='negotiation_pkey')
    )
    op.create_table('order',
    sa.Column('action', sa.Enum('ATTACK', 'DEVELOP', 'SHIELD', 'CREATE', 'ECO', 'SANCTIONS', 'INVENT', 'NEGOTIATE', name='OrderType'), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('argument', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action', 'planet_id', 'round', 'argument', name='order_pkey')
    )
    op.create_table('sanction',
    sa.Column('planet_from', sa.Integer(), nullable=False),
    sa.Column('planet_to', sa.Integer(), nullable=False),
    sa.Column('num_round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_from'], ['planet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planet_to'], ['planet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('planet_from', 'planet_to', 'num_round', name='sanction_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanction')
    op.drop_table('order')
    op.drop_table('negotiation')
    op.drop_table('city')
    op.drop_table('planet')
    op.drop_table('round_info')
    op.drop_table('player')
    op.drop_table('admin')
    op.drop_table('game')
    # ### end Alembic commands ###
