name: Linter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        cache: 'poetry'
          
    - name: Install environment
      run: |
        pip install poetry
        poetry install

    - name: Linter check
      run: make lint
